name: Bot Minecraft 24/7

on:
  workflow_dispatch:
  schedule:
    # Executa a cada 5 horas para manter o bot rodando no GitHub
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências (Mineflayer)
        run: |
          npm init -y
          npm install mineflayer minecraft-protocol

      - name: Rodar Bot
        run: node bot.js
